%{ if ingress != null ~}
ingress:
  enabled: true
  className: ${ingress.class_name}
  hosts:
    - host: ${ingress.host}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - ${ingress.host}
      secretName: ${ingress.tls.secret_name}

certManager:
  certificate:
    create: ${ingress.tls.create_certificate}
  issuer:
    create: ${ingress.tls.create_issuer}
    email: ${ingress.tls.issuer_email}
%{ endif ~}

%{ if admin_emails ~}
auth:
  adminEmails:
%{ for admin_email in admin_emails ~}
    - "${admin_email}"
%{ endfor ~}
%{ endif ~}

api:
  enabledVersions:
%{ if api_enable_v1 ~}
    - v1
%{ endif ~}
    - v2

%{ if chart_discovery != null ~}
chartDiscovery:
  ecr:
    queueName: ${chart_discovery.queue_name}
    regionName: ${chart_discovery.queue_region}
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ${chart_discovery.iam_role_arn}
%{ endif ~}

%{ if k8s_agents != [] ~}
k8sAgents:
%{ for k8s_agent in k8s_agents ~}
  - name: ${k8s_agent.name}
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${k8s_agent.iam_role_arn}
%{ endfor ~}
%{ endif ~}

postgresql:
  enabled: ${use_chart_db}
  databaseUrlOverride: ${db_url_override}
